version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: daker
      POSTGRES_PASSWORD: example
      POSTGRES_DB: recipe

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
